In [9]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

X = np.array([[2, 8, 4, 5], [6, 3, 0, 8], [5, 4, 9, 1]])

# 1. 训练集fit标准化
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print(X_scaled)
print('--' * 50)

# 此时 X_scaled 的每一列方差≈1
print(np.var(X_scaled,axis=0))
print('--' * 50)

# 2. 在标准化后的数据上做PCA
pca = PCA(n_components=0.9)
X_pca = pca.fit_transform(X_scaled)
print(X_pca)
print('-' * 50)
print(pca.components_)
print('--' * 50)

# PCA得到的主成分方差，不再等于1，从大到小排列
print(pca.explained_variance_)
print('--' * 50)
print(pca.explained_variance_ratio_)

[[-1.37281295  1.38873015 -0.09053575  0.11624764]
 [ 0.98058068 -0.9258201  -1.1769647   1.16247639]
 [ 0.39223227 -0.46291005  1.26750044 -1.27872403]]
----------------------------------------------------------------------------------------------------
[1. 1. 1. 1.]
----------------------------------------------------------------------------------------------------
[[-1.27419212  1.48705463]
 [ 2.12371519  0.21239673]
 [-0.84952306 -1.69945137]]
--------------------------------------------------
[[ 0.51032476 -0.48756077 -0.50484844  0.49697201]
 [-0.48590088  0.51611019 -0.49346516  0.50400668]]
----------------------------------------------------------------------------------------------------
[3.4277106 2.5722894]
----------------------------------------------------------------------------------------------------
[0.5712851 0.4287149]


In [18]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

X = np.array([[2, 8, 4, 5], [6, 3, 0, 8], [5, 4, 9, 1]])

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=0.9)
X_pca = pca.fit_transform(X_scaled)

print("=== components_： 权重矩阵（特征向量）===")
print(pca.components_)
print("形状", pca.components_.shape)

print("\n=== explained_variance_ 特征值 ===")
print(pca.explained_variance_)
# 特征值大小：代表对应主成分携带信息量

=== components_： 权重矩阵（特征向量）===
[[ 0.51032476 -0.48756077 -0.50484844  0.49697201]
 [-0.48590088  0.51611019 -0.49346516  0.50400668]]
形状 (2, 4)

=== explained_variance_ 特征值 ===
[3.4277106 2.5722894]
